# Changes here will be overwritten by Copier
_commit: 28184e6
_src_path: https://github.com/lenskit/lk-project-template.git
package_name: progress_api
project_name: progress-api
require_lint: true
start_year: 2023
