# Changes here will be overwritten by Copier
_commit: f9f4225
_src_path: https://github.com/lenskit/lk-project-template.git
owner: Drexel University and contributors
package_name: progress_api
project_descr: ''
project_name: progress-api
project_title: Progress API
require_lint: true
start_year: 2023
typecheck: true
