# Changes here will be overwritten by Copier
_commit: 4a8d7e8
_src_path: https://github.com/lenskit/lk-project-template.git
package_name: progress_api
project_name: progress-api
project_title: Progress API
require_lint: true
start_year: 2023
